### ISSUE TITLE
[ The road to RC ] Todo's

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/SickRage#392]
This list will be used as a roadmap towards RC and later the merge to Master.
The list is meant for finishing already started features or bugfixes.

### General
- [x] Bump Database version

### Manual Search
- [x] Episode snatched with manual search doesn't change its status to snatched in show overview  https://github.com/pymedusa/SickRage/pull/451
- [x] Result snatches should be queued in a separate thread, as opposed to currently being queued in the searchQueueScheduler thread. #395 
- [x] A forced search (also used by manual search) should be queued in a separate thread, as opposed to currently being queued in the searchQueueScheduler thread. #366 
- [x] The snatchSelection page should display snatch/download/failed download history, like how it's displayed in the displayShow page.
- [X] Disable season search if season has still unaired episodes
- [X] Add season pack manual searching #389

### General bugs
- [x] ~~Fix URL limit (I guess that's about  https://github.com/pymedusa/SickRage/pull/434)~~
- [x] Queue show removals, as to wait for all threads to finish and make sure it can be removed safe #244 #567 
- [x] Fix unicode issues during post processing #390 
- [x] Fix tmdb certificate error https://github.com/pymedusa/SickRage/pull/145/commits/a6a504a12353f67bacf9ab42ad6d7210e2c13530
- [x] Not saving NZB cats
- [x] Check IMDB for showinfo results in keyErrors like KeyError: 'runtimes' #379 #391 #385
- [x] Updated ConfigObj does not properly save non-ascii values. (Revert for RC until we can finish the ConfigObj validators) @medariox can you verify this is fixed now?

### Subliminal
- [x] Limit the amount of "2016-04-15 10:18:22 DEBUG    FINDSUBTITLES :: [1f87e70] Found subtitle" messages. Found subtitle isn't really "informative". @ratoaq2 
- [x] Improve performance or throttle subtitleFinder thread cpu usage. As a search is bringing my dualcore Atom on it knees. Wonder what it will do to a low end arm device. https://github.com/pymedusa/SickRage/pull/472

@pymedusa/contributors

**Comment by fernandog** [comment]
@p0psicles 

"The snatchSelection page should display snatch/download/failed download history, like how it's displayed in the displayShow page" - with this, page will take a LONG TIME run. For each result, we will need to query full history of user

**Comment by labrys** [comment]
You don't need to query the full history, just the history for that particular episode.

**Comment by fernandog** [comment]
@p0psicles need only one fix for manual search
main thread updated

**Comment by p0psicles** [comment]
Yeah and we still need allot of bugfixes before we can start moving to RC1.

**Comment by OmgImAlexis** [comment]
If anyone needs access to our pymedusa.com email let me know as I have it setup. It'll look a little better to use that instead of a personal email.w

**Comment by p0psicles** [comment]
If we focus on this list from now, we're very close to release: https://github.com/pymedusa/SickRage/milestones/RC1
But then we should lay low on the "improvements" and definitely stop working on new features.

@pymedusa/developers What do you guys think?

**Comment by ratoaq2** [comment]
Related to: 

>  Limit the amount of "2016-04-15 10:18:22 DEBUG FINDSUBTITLES :: [1f87e70] Found subtitle" messages. Found subtitle isn't really "informative". @ratoaq2

This is what subliminal will log:: 
https://github.com/Diaoul/subliminal/blob/develop/subliminal/providers/legendastv.py#L426
https://github.com/Diaoul/subliminal/blob/develop/subliminal/providers/legendastv.py#L94
`Found subtitle <%s [%s] %r>' % (self.__class__.__name__, self.id, self.name)`

The issue is that the web page that shows the logs doesn't escape the log and the information between `<`and `>` is not displayed. What is the expectation here? To fix it and display the correct log message with all characters and information or to suppress it?

**Comment by labrys** [comment]
@ratoaq2 I would think try displaying.  If we find that's still too verbose we can suppress it.  Either imo would be better than an uninformative message.

**Comment by labrys** [comment]
v0.1.0rc1 complete.  If no issues present in the next couple days lets RTM.
