### ISSUE TITLE
[ TODO ] Milestone v0.1.1

### ISSUE THREAD

**Issue by labrys** [pymedusa/SickRage#605]
This is to discuss status of v0.1.1 and items that should/should not be included.

### User Interface
* [x] Update news
* [x] Update changelog
* [ ] ~~Fanart~~ -> 0.1.2
* [ ] Clean up mako (ongoing)
* [ ] ~~I18n and l10n - Lay foundation (e.g. gettext calls in UI etc)~~ -> 0.1.2
* [ ] ~~Add Anidb recommended lists~~ -> 0.1.2
* [x] Increase privacy and add setting to control privacy levels

### General
* [x] Web server modularization (ongoing)
* [ ] ~~Cleanup Trakt api~~ -> 0.1.2
* [x] Add simpleanidb lib
* [ ] ~~New recommended lists structure~~ -> 0.1.2
* [ ] ~~Replace messages with websockets~~ -> 0.1.2
* [x] Remove simplejson #598 #643
* [x] Fix nfo parsing #629 

### Search Providers
* [x] Fix torrentday #641 
* [x] Fix speedcd #642 
* [x] RARBG logging #616

**Comment by labrys** [comment]
Let's try for some quicker releases, unless we have some major features ready to merge.  I'm setting this milestone for v0.1.1 to May 29th.  We can adjust if needed.

**Comment by p0psicles** [comment]
@labrys This is a bit more realistic for next release. Keep in mind, that if you want to keep this pace, 0.1.2 is also at capacity.

**Comment by labrys** [comment]
@p0psicles that was closer to what I was looking at, for this release, which is why i had planned on such a quick turn-around.  We don't necessarily need every release to be at such a fast pace, however those items should be fairly quick to accomplish.

**Comment by fernandog** [comment]
@p0psicles dont know if you follow discussion with @jxer but he suggested to rename button "force search" in snatchSelection to something else to not confuse with "forced search"

We came up with:
"Fetch more"
"Search more"
"More Search Results"

and add a hint to the button so users know that when you "forced search", the setting "manual search providers will be used"

**Comment by wimpyrbx** [comment]
for some reason i'm unable to get backstretch javascript running to display fanart.
for sickrage (miigotu) i used http://srobbin.com/jquery-plugins/backstretch/

there is opacity setting that can be used and in sickrage (miigotu) it was done by making the user settings to decide level of opacity in steps of 0.1 (0.1 being 10% and 0.8 being 80%)

to display the fanart i pointed to this routine which i have confirmed working when testing with <img src=".....">
${srRoot}/showPoster/?show=${show.indexerid}&amp;which=fanart

i have no idea why it's not working on medusa like i did it, but i know miigotu did some hefty changes moving the js file into core.js or something etc.. well i'm at a loss here as to how to re-create this at the moment :(
